# Generated by Django 3.0.7 on 2020-06-16 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcontrib', models.IntegerField(default=0, verbose_name='Dictionary contributions')),
                ('rcontrib', models.IntegerField(default=0, verbose_name='Resource contributions')),
                ('points', models.IntegerField(default=0)),
                ('learning_language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learners', to='learning.LearningLanguage')),
                ('native_language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='natives', to='learning.Language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
