# Generated by Django 3.0.7 on 2020-06-16 13:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20200616_1337'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSetting',
            new_name='UserConfiguration',
        ),
    ]
