# Generated by Django 3.0.7 on 2020-06-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='flag',
            field=models.FileField(help_text='Images must be in SVG format and, if possible, under the filename CODE.svg, where CODE represents the corresponding ISO 639-1 code.', upload_to='learning/static/learning/img/flags/'),
        ),
    ]
