# Generated by Django 3.0.7 on 2020-06-19 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_auto_20200618_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelmessage',
            name='sent_by',
        ),
        migrations.RemoveField(
            model_name='channelmessage',
            name='thread',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='first',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='second',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='sent_by',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='thread',
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
        migrations.DeleteModel(
            name='ChannelMessage',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
