# Generated by Django 3.0.7 on 2020-06-22 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0003_auto_20200619_1958'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemma', models.CharField(max_length=120)),
                ('definition', models.TextField(blank=True, null=True)),
                ('etymology', models.TextField(blank=True, null=True)),
                ('example_sent1', models.CharField(blank=True, max_length=500, null=True, verbose_name='Example Sentence 1')),
                ('example_sent2', models.CharField(blank=True, max_length=500, null=True, verbose_name='Example Sentence 2')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.ManyToManyField(related_name='translations', to='dictionary.DictionaryTerm')),
            ],
        ),
        migrations.CreateModel(
            name='TranslationReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('submitted_time', models.DateTimeField(auto_now_add=True)),
                ('base_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_reports', to='dictionary.DictionaryTerm')),
                ('translation_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Translation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translation_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DictionaryReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('part', models.CharField(choices=[('lemma', 'Term lemma'), ('definition', 'Term definition'), ('etymology', 'Term etymology'), ('example_sent1', 'Example Sentence 1'), ('example_sent2', 'Example Sentence 2')], max_length=15)),
                ('submitted_time', models.DateTimeField(auto_now_add=True)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='dictionary.DictionaryTerm')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dictionary_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
