# Generated by Django 3.0.7 on 2020-06-26 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionary', '0002_auto_20200624_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionaryterm',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dictionaryterm',
            name='definition',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
