# Generated by Django 3.0.7 on 2020-06-28 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_auto_20200626_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionaryreport',
            name='custom',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dictionaryreport',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='translationreport',
            name='custom',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='translationreport',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='translationreport',
            name='target_term',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reported_translation', to='dictionary.DictionaryTerm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dictionaryreport',
            name='reason',
            field=models.CharField(choices=[('content_incorrect', 'The content is incorrect.'), ('content_inappropriate', 'The content is inappropriate or NSFW.'), ('content_spam', 'The content is spam or misleading.'), ('content_mistake', 'The content contains grammatical/orthographic errors.'), ('content_ambiguous', 'The content is ambiguous'), ('content_other', 'Other (custom).')], max_length=50),
        ),
        migrations.AlterField(
            model_name='translationreport',
            name='base_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translation_reports', to='dictionary.DictionaryTerm'),
        ),
        migrations.AlterField(
            model_name='translationreport',
            name='reason',
            field=models.CharField(choices=[('content_incorrect', 'The content is incorrect.'), ('content_inappropriate', 'The content is inappropriate or NSFW.'), ('content_spam', 'The content is spam or misleading.'), ('content_mistake', 'The content contains grammatical/orthographic errors.'), ('content_ambiguous', 'The content is ambiguous'), ('content_other', 'Other (custom).')], max_length=50),
        ),
    ]
